# adopted from https://github.com/MihailRis/VoxelEngine-Cpp
name: Build and Release

on: [push]

permissions:
  contents: write

jobs:
  build_release:
    name: Build Release
    uses: ./.github/workflows/build.yml

  create_release:
    needs: build_release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: vot
          pattern: vot-*
          merge-multiple: true
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          name: ${{ github.sha }}
          draft: true
          prerelease: false
          files: |
            vot/vot.user.js
            vot/vot-min.user.js
            vot/vot-cloudflare.user.js
            vot/vot-cloudflare-min.user.js